name: CI Pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg integrate install
          .\vcpkg install libpqxx:x64-windows --classic

      - name: Download Crow header
        run: |
          mkdir include\crow
          curl -L https://raw.githubusercontent.com/CrowCpp/Crow/master/include/crow_all.h -o include\crow\crow_all.h

      - name: Set up MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build solution in Debug
        env:
          VCPKG_ROOT: ${{ github.workspace }}\vcpkg
        run: msbuild "Project5_HR/Project5_HR.sln" /p:Configuration=Debug /p:Platform=x64 /t:Build

      - name: Run unit tests
        run: |
          vstest.console.exe "Project5_HR/x64/Debug/Project5_HR_Test.dll"

  clang-tidy-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run Clang-Tidy
        uses: ZedThree/clang-tidy-review@v0.21.0
        with:
          cmake_command: cmake . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON 
          build_dir: build
          token: ${{ secrets.GITHUB_TOKEN }}
          run: cpplint --recursive .
